// playersData.js
export const playersData = {
    G: [
      { name: "Stephen Curry", ratings: { 
        'Three Point Tendancy': 100,
        'Three Point Shooting': 100,
        'Mid-Range Tendancy': 60,
        'Mid-Range Shooting': 100,
        'Driving Tendancy': 75,
        'Finishing': 90,
        'Foul Drawing': 20,
        'Free Throw Shooting': 100,
        'Overall Shooting Volume': 90,

        'Passing Tendancy': 70,
        'Passing Accuracy': 70,
        'Rebounding': 45,
        'Rim Protection': 5,
        'Deflections': 80,

        'Height': 30,
        'Offense': 100,
        'Defense': 60,
        }},
    { name: "Luka Doncic", ratings: { 
        'Three Point Tendancy': 80,
        'Three Point Shooting': 80,
        'Mid-Range Tendancy': 60,
        'Mid-Range Shooting': 70,
        'Driving Tendancy': 90,
        'Finishing': 85,
        'Foul Drawing': 80,
        'Free Throw Shooting': 90,
        'Overall Shooting Volume': 95,

        'Passing Tendancy': 90,
        'Passing Accuracy': 75,
        'Rebounding': 75,
        'Rim Protection': 10,
        'Deflections': 50,

        'Height': 60,
        'Offense': 90,
        'Defense': 40,
        }},
    { name: "Shai Gilgeous-Alexander", ratings: { 
        'Three Point Tendancy': 65,
        'Three Point Shooting': 70,
        'Mid-Range Tendancy': 90,
        'Mid-Range Shooting': 85,
        'Driving Tendancy': 95,
        'Finishing': 95,
        'Foul Drawing': 95,
        'Free Throw Shooting': 90,
        'Overall Shooting Volume': 95,

        'Passing Tendancy': 55,
        'Passing Accuracy': 50,
        'Rebounding': 70,
        'Rim Protection': 60,
        'Deflections': 85,

        'Height': 55,
        'Offense': 90,
        'Defense': 75,
        }},
    { name: "Anthony Edwards", ratings: { 
        'Three Point Tendancy': 80,
        'Three Point Shooting': 80,
        'Mid-Range Tendancy': 40,
        'Mid-Range Shooting': 80,
        'Driving Tendancy': 90,
        'Finishing': 90,
        'Foul Drawing': 75,
        'Free Throw Shooting': 75,
        'Overall Shooting Volume': 90,

        'Passing Tendancy': 30,
        'Passing Accuracy': 30,
        'Rebounding': 70,
        'Rim Protection': 60,
        'Deflections': 60,

        'Height': 40,
        'Offense': 85,
        'Defense': 70,
        }},
    ],
    F: [
    { name: "Jayson Tatum", ratings: { 
        'Three Point Tendancy': 70,
        'Three Point Shooting': 70,
        'Mid-Range Tendancy': 50,
        'Mid-Range Shooting': 70,
        'Driving Tendancy': 90,
        'Finishing': 80,
        'Foul Drawing': 75,
        'Free Throw Shooting': 85,
        'Overall Shooting Volume': 80,

        'Passing Tendancy': 60,
        'Passing Accuracy': 60,
        'Rebounding': 75,
        'Rim Protection': 50,
        'Deflections': 75,

        'Height': 70,
        'Offense': 90,
        'Defense': 75,
        }},
    { name: "Kevin Durant", ratings: { 
        'Three Point Tendancy': 80,
        'Three Point Shooting': 90,
        'Mid-Range Tendancy': 95,
        'Mid-Range Shooting': 100,
        'Driving Tendancy': 70,
        'Finishing': 80,
        'Foul Drawing': 70,
        'Free Throw Shooting': 95,
        'Overall Shooting Volume': 100,

        'Passing Tendancy': 40,
        'Passing Accuracy': 60,
        'Rebounding': 75,
        'Rim Protection': 65,
        'Deflections': 70,

        'Height': 90,
        'Offense': 100,
        'Defense': 70,
        }},
    { name: "Lebron James", ratings: { 
        'Three Point Tendancy': 70,
        'Three Point Shooting': 85,
        'Mid-Range Tendancy': 85,
        'Mid-Range Shooting': 80,
        'Driving Tendancy': 100,
        'Finishing': 100,
        'Foul Drawing': 90,
        'Free Throw Shooting': 75,
        'Overall Shooting Volume': 85,

        'Passing Tendancy': 80,
        'Passing Accuracy': 75,
        'Rebounding': 80,
        'Rim Protection': 70,
        'Deflections': 80,

        'Height': 80,
        'Offense': 90,
        'Defense': 85,
        }},
    ],
    C: [
        { name: "Nikola Jokic", ratings: { 
            'Three Point Tendancy': 50,
            'Three Point Shooting': 80,
            'Mid-Range Tendancy': 20,
            'Mid-Range Shooting': 80,
            'Driving Tendancy': 95,
            'Finishing': 90,
            'Foul Drawing': 80,
            'Free Throw Shooting': 80,
            'Overall Shooting Volume': 85,
    
            'Passing Tendancy': 100,
            'Passing Accuracy': 95,
            'Rebounding': 90,
            'Rim Protection': 80,
            'Deflections': 40,
    
            'Height': 90,
            'Offense': 100,
            'Defense': 45,
            }},
        { name: "Rudy Gobert", ratings: { 
            'Three Point Tendancy': 0,
            'Three Point Shooting': 0,
            'Mid-Range Tendancy': 20,
            'Mid-Range Shooting': 20,
            'Driving Tendancy': 70,
            'Finishing': 70,
            'Foul Drawing': 50,
            'Free Throw Shooting': 20,
            'Overall Shooting Volume': 40,
    
            'Passing Tendancy': 20,
            'Passing Accuracy': 30,
            'Rebounding': 95,
            'Rim Protection': 100,
            'Deflections': 85,
    
            'Height': 95,
            'Offense': 30,
            'Defense': 95,
            }},
        { name: "Victor Wembanyama", ratings: { 
            'Three Point Tendancy': 60,
            'Three Point Shooting': 75,
            'Mid-Range Tendancy': 40,
            'Mid-Range Shooting': 80,
            'Driving Tendancy': 70,
            'Finishing': 70,
            'Foul Drawing': 75,
            'Free Throw Shooting': 80,
            'Overall Shooting Volume': 85,
    
            'Passing Tendancy': 60,
            'Passing Accuracy': 70,
            'Rebounding': 100,
            'Rim Protection': 100,
            'Deflections': 90,
    
            'Height': 100,
            'Offense': 75,
            'Defense': 100,
            }},
    ]
  };
  